### ISSUE TITLE
failed to get identity from cyberconnect

### ISSUE THREAD

**Issue by joecwu** [solfren-team/solfren-web-sdk#28]
received the error below when using `Profile.get`
```
failed to identity ClientError: Server Internal Error: {"response":{"errors":[{"message":"Server Internal Error"}],"data":null,"status":200,"headers":{}},"request":{"query":"\n      query($address: String!) {\n        identity(address: $address) {\n          followerCount\n          followingCount\n          twitter {\n            handle\n            avatar\n            verified\n            tweetId\n            source\n            followerCount\n          }\n          github {\n            username\n            gistId\n            userId\n          }\n        }\n      }\n    ","variables":{"address":"undefined"}}}
    at /Users/joecwu/projects/crypto/solfren/solfren-remix/node_modules/graphql-request/src/index.ts:410:11
    at step (/Users/joecwu/projects/crypto/solfren/solfren-remix/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/Users/joecwu/projects/crypto/solfren/solfren-remix/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/Users/joecwu/projects/crypto/solfren/solfren-remix/node_modules/graphql-request/dist/index.js:35:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  response: {
    errors: [ [Object] ],
    data: null,
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  },
  request: {
    query: '\n' +
      '      query($address: String!) {\n' +
      '        identity(address: $address) {\n' +
      '          followerCount\n' +
      '          followingCount\n' +
      '          twitter {\n' +
      '            handle\n' +
      '            avatar\n' +
      '            verified\n' +
      '            tweetId\n' +
      '            source\n' +
      '            followerCount\n' +
      '          }\n' +
      '          github {\n' +
      '            username\n' +
      '            gistId\n' +
      '            userId\n' +
      '          }\n' +
      '        }\n' +
      '      }\n' +
      '    ',
    variables: { address: 'undefined' }
  }
```

**Comment by joecwu** [comment]
https://docs.cyberconnect.me/V1/cyberconnect-api/graphql-api/identity/
看起來格式不太一樣，另外發現也少指定 `network: SOLANA`.
